version: 0.{build}
skip_tags: true
max_jobs: 1
image: Visual Studio 2017
configuration: Release
platform: x86
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
build:
  project: build/III.VC.SA.WindowedMode.sln
  verbosity: minimal
before_package:
- cmd: >-
    cd data

    release.bat
artifacts:
- path: data/III.VC.SA.WindowedMode.zip
  name: III.VC.SA.WindowedMode.zip
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: III.VC.SA.WindowedMode v$(appveyor_build_version)
  description: '- [Readme](https://github.com/niresh1234/III.VC.SA.WindowedMode/blob/master/README.md)'
  auth_token:
    secure: EwVN+VFM4Zs+LlEv5iFjFwMudb8F3ZAl37yLr53vIcIfTUvqV7VMWXtc9A7JTelg
  artifact: III.VC.SA.WindowedMode.zip
