version: 0.{build}
skip_tags: true
max_jobs: 1
image: Visual Studio 2017
configuration: Release
platform: x86
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
build:
  project: build/III.VC.SA.WindowedMode.sln
  verbosity: minimal
before_package:
- cmd: >-
    cd data

    release.bat
artifacts:
- path: data/III.VC.SA.WindowedMode.zip
  name: III.VC.SA.WindowedMode.zip
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: III.VC.SA.WindowedMode v$(appveyor_build_version)
  description: '- [Readme](https://github.com/ThirteenAG/III.VC.SA.WindowedMode/blob/v1.0/README.md)'
  auth_token:
    secure: ZKssQkW3NX4DF6cHuUdBvsH6bwvD7ga+MncCvxoMKl+aV3QQfXmgcomcqvJKZ4qC
  artifact: III.VC.SA.WindowedMode.zip
